// Developer surfaces deliberately do not participate in next-intl message parity.
export const developerEnglish = {
  wrench: "Developer tools",
  close: "Close",
  empty: "No tools available here.",
  gmRequired: "Campaign GM required.",
  inactive: "Active campaign required.",
  now: "Now",
  started: "Started",
  duration: "Duration",
  players: "Players",
  gm: "GM",
  player: (slot: number | null) => `Player ${slot ?? "—"}`,
  start: "Start diagnostics",
  stop: "Stop & export",
  collecting: "Collecting final checkpoints…",
  exporting: "Building diagnostic ZIP…",
  retry: "Retry export",
  download: "ZIP download initiated. Keep the file before closing this window.",
  cleanupPending: "Download initiated; temporary data cleanup will retry automatically.",
  playerTitle: "Technical diagnostics active",
  playerNotice: "Connection statistics only. No audio/video recording.",
  unavailable: "Diagnostics are unavailable. Retry when connected.",
  denied: "Diagnostic access is unavailable or has been revoked.",
  bufferError: "Local diagnostic storage failed. The run may be partial.",
  status: {
    "○": "Not collecting",
    "…": "Waiting for validated data",
    "✓": "Validated progress received",
    "!": "Missing, stale, or incomplete diagnostics",
  },
} as const;
